services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - database


  database:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}